{{- if and .Values.serviceMesh.enabled (eq .Values.serviceMesh.provider "linkerd") }}
---
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: {{ include "avon.control.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  labels:
    {{- include "avon.control.labels" . | nindent 4 }}
spec:
  routes:
    - name: gRPC
      condition:
        pathRegex: /.*
      timeout: 10s
---
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: {{ include "avon.ca.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  labels:
    {{- include "avon.ca.labels" . | nindent 4 }}
spec:
  routes:
    - name: gRPC
      condition:
        pathRegex: /.*
      timeout: 30s
---
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: {{ include "avon.adminApi.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  labels:
    {{- include "avon.adminApi.labels" . | nindent 4 }}
spec:
  routes:
    - name: HTTP
      condition:
        pathRegex: /.*
      timeout: 30s
{{- end }}
