apiVersion: v1
kind: Service
metadata:
  name: {{ include "avon.ca.fullname" . }}
  labels:
    {{- include "avon.ca.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ca.service.type }}
  ports:
    - port: {{ .Values.ca.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "avon.ca.selectorLabels" . | nindent 4 }}
