//! Rotating authentication tokens for device identity.
//!
//! This module implements a rotating token system similar to car key rolling codes.
//! Each token rotation derives a new token from the current token combined with
//! nonces from both client and server, providing:
//!
//! - **Replay protection**: Each token is unique and derived from unpredictable nonces
//! - **Implicit liveness**: Successful rotation proves both parties are online
//! - **Forward secrecy**: Compromising a token doesn't reveal previous tokens
//!
//! # Car Key Rolling Code Analogy
//!
//! Like a car key fob that changes its code after each use, the rotating token
//! changes after each authentication. The server and client maintain synchronized
//! state, and each rotation produces a new unpredictable token.
//!
//! # Grace Period (Previous Token)
//!
//! Network issues can cause rotation messages to be lost. If the client rotates
//! but the server doesn't receive the confirmation, they become desynchronized.
//! The grace period allows the previous token to remain valid for one rotation
//! cycle, giving time to detect and recover from desync.
//!
//! # Replay Protection
//!
//! Each rotation incorporates:
//! - Server nonce (unpredictable, prevents client-side replay)
//! - Client nonce (unpredictable, prevents server-side replay)
//! - Timestamp (bounds validity window)
//! - Sequence number (detects skipped rotations)
//!
//! # Resync Procedure
//!
//! If tokens get out of sync:
//! 1. Server detects auth failure (neither current nor previous matches)
//! 2. Server initiates resync by sending a challenge
//! 3. Client proves identity using a backup authentication method
//! 4. Both parties reset to a new shared seed
//!
//! # Example
//!
//! ```
//! use avon_crypto::token::{RotatingToken, ServerTokenState, TokenRotationInput, TokenVerifyResult};
//!
//! // Initial shared seed (in practice, derived from key exchange)
//! let seed = [0x42u8; 32];
//! let device_id = [0x01u8; 16];
//!
//! // Create client and server token states
//! let mut client = RotatingToken::new(seed);
//! let mut server = ServerTokenState::new(device_id, seed);
//!
//! // Verify initial token
//! assert!(matches!(server.verify(client.current()), TokenVerifyResult::Current));
//!
//! // Server generates rotation input
//! let (input, _server_nonce) = server.generate_rotation_input();
//!
//! // Both sides rotate
//! let client_new = client.rotate(&input);
//! let server_new = server.complete_rotation(&input);
//!
//! // They derive the same new token
//! assert_eq!(client_new, server_new);
//! ```

use zeroize::{Zeroize, ZeroizeOnDrop};

use crate::hmac::{hmac_sha256, hmac_sha256_verify};
use crate::kdf::hkdf_sha256;
use crate::random::random_bytes_fixed;

/// Domain separator for token rotation.
const TOKEN_ROTATE_INFO: &[u8] = b"AVON-token-rotate-v1";

/// Result of verifying a token against the current state.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TokenVerifyResult {
    /// Token matches the current expected token.
    Current,
    /// Token matches the previous token (grace period).
    /// This indicates a possible desync - the client may have missed a rotation.
    Previous,
    /// Token does not match either current or previous.
    Invalid,
}

/// Input data for a token rotation operation.
///
/// Both client and server must use identical rotation inputs to derive
/// the same next token.
#[derive(Debug, Clone)]
pub struct TokenRotationInput {
    /// Random nonce generated by the server.
    pub server_nonce: [u8; 32],
    /// Random nonce generated by the client.
    pub client_nonce: [u8; 32],
    /// Unix timestamp of the rotation.
    pub timestamp: u64,
}

impl TokenRotationInput {
    /// Creates a new rotation input with the given nonces and timestamp.
    pub fn new(server_nonce: [u8; 32], client_nonce: [u8; 32], timestamp: u64) -> Self {
        Self {
            server_nonce,
            client_nonce,
            timestamp,
        }
    }
}

/// Rotating authentication token for device identity.
///
/// This struct maintains the client-side state for the rotating token protocol.
/// It stores the current token, optionally the previous token for grace period
/// recovery, and the sequence number.
///
/// # Security
///
/// The token material is zeroized on drop to prevent memory disclosure.
#[derive(Zeroize, ZeroizeOnDrop)]
pub struct RotatingToken {
    current: [u8; 32],
    previous: Option<[u8; 32]>,
    sequence: u64,
}

impl RotatingToken {
    /// Creates a new rotating token from an initial seed.
    ///
    /// The seed should be derived from a secure key exchange and should
    /// be unique per device.
    ///
    /// # Example
    ///
    /// ```
    /// use avon_crypto::token::RotatingToken;
    ///
    /// let seed = [0x42u8; 32];
    /// let token = RotatingToken::new(seed);
    /// assert_eq!(token.sequence(), 0);
    /// ```
    pub fn new(initial_seed: [u8; 32]) -> Self {
        Self {
            current: initial_seed,
            previous: None,
            sequence: 0,
        }
    }

    /// Returns a reference to the current token.
    ///
    /// # Example
    ///
    /// ```
    /// use avon_crypto::token::RotatingToken;
    ///
    /// let seed = [0x42u8; 32];
    /// let token = RotatingToken::new(seed);
    /// assert_eq!(token.current(), &seed);
    /// ```
    pub fn current(&self) -> &[u8; 32] {
        &self.current
    }

    /// Returns the current sequence number.
    ///
    /// The sequence number increments with each rotation and can be used
    /// to detect skipped rotations.
    ///
    /// # Example
    ///
    /// ```
    /// use avon_crypto::token::{RotatingToken, TokenRotationInput};
    ///
    /// let mut token = RotatingToken::new([0x42u8; 32]);
    /// assert_eq!(token.sequence(), 0);
    ///
    /// let input = TokenRotationInput::new([0u8; 32], [1u8; 32], 1000);
    /// token.rotate(&input);
    /// assert_eq!(token.sequence(), 1);
    /// ```
    pub fn sequence(&self) -> u64 {
        self.sequence
    }

    /// Rotates the token using the provided input.
    ///
    /// This derives a new token from:
    /// - Current token
    /// - Server nonce
    /// - Client nonce
    /// - Timestamp
    /// - Sequence number
    ///
    /// The current token becomes the previous token (for grace period),
    /// and the derived token becomes the new current token.
    ///
    /// # Returns
    ///
    /// The new current token.
    ///
    /// # Example
    ///
    /// ```
    /// use avon_crypto::token::{RotatingToken, TokenRotationInput};
    ///
    /// let mut token = RotatingToken::new([0x42u8; 32]);
    /// let input = TokenRotationInput::new([0u8; 32], [1u8; 32], 1000);
    ///
    /// let new_token = token.rotate(&input);
    /// assert_ne!(new_token, [0x42u8; 32]); // Token changed
    /// assert_eq!(token.sequence(), 1);
    /// ```
    pub fn rotate(&mut self, input: &TokenRotationInput) -> [u8; 32] {
        let new_token = derive_next_token(
            &self.current,
            &input.server_nonce,
            &input.client_nonce,
            input.timestamp,
            self.sequence,
        );

        self.previous = Some(self.current);
        self.current = new_token;
        self.sequence += 1;

        new_token
    }

    /// Verifies a token against the current state.
    ///
    /// Returns `Current` if the token matches the current token,
    /// `Previous` if it matches the previous token (grace period),
    /// or `Invalid` if it matches neither.
    ///
    /// # Example
    ///
    /// ```
    /// use avon_crypto::token::{RotatingToken, TokenRotationInput, TokenVerifyResult};
    ///
    /// let mut token = RotatingToken::new([0x42u8; 32]);
    /// let current = *token.current();
    ///
    /// assert!(matches!(token.verify(&current), TokenVerifyResult::Current));
    ///
    /// // After rotation, old token is Previous
    /// let input = TokenRotationInput::new([0u8; 32], [1u8; 32], 1000);
    /// token.rotate(&input);
    ///
    /// assert!(matches!(token.verify(&current), TokenVerifyResult::Previous));
    /// ```
    pub fn verify(&self, token: &[u8; 32]) -> TokenVerifyResult {
        // Use constant-time comparison
        if constant_time_eq(&self.current, token) {
            return TokenVerifyResult::Current;
        }

        if let Some(ref prev) = self.previous {
            if constant_time_eq(prev, token) {
                return TokenVerifyResult::Previous;
            }
        }

        TokenVerifyResult::Invalid
    }

    /// Computes an authentication tag over the given data.
    ///
    /// Uses HMAC-SHA256 with the current token as the key.
    ///
    /// # Example
    ///
    /// ```
    /// use avon_crypto::token::RotatingToken;
    ///
    /// let token = RotatingToken::new([0x42u8; 32]);
    /// let data = b"important message";
    /// let tag = token.compute_auth_tag(data);
    ///
    /// assert!(token.verify_auth_tag(data, &tag));
    /// ```
    pub fn compute_auth_tag(&self, data: &[u8]) -> [u8; 32] {
        hmac_sha256(&self.current, data)
    }

    /// Verifies an authentication tag over the given data.
    ///
    /// Tries the current token first, then the previous token if available.
    /// Uses constant-time comparison.
    ///
    /// # Example
    ///
    /// ```
    /// use avon_crypto::token::{RotatingToken, TokenRotationInput};
    ///
    /// let mut token = RotatingToken::new([0x42u8; 32]);
    /// let data = b"important message";
    /// let tag = token.compute_auth_tag(data);
    ///
    /// // Tag verifies with current token
    /// assert!(token.verify_auth_tag(data, &tag));
    ///
    /// // After rotation, tag still verifies (using previous token)
    /// let input = TokenRotationInput::new([0u8; 32], [1u8; 32], 1000);
    /// token.rotate(&input);
    /// assert!(token.verify_auth_tag(data, &tag));
    /// ```
    pub fn verify_auth_tag(&self, data: &[u8], tag: &[u8; 32]) -> bool {
        // Try current token
        if hmac_sha256_verify(&self.current, data, tag) {
            return true;
        }

        // Try previous token if available
        if let Some(ref prev) = self.previous {
            if hmac_sha256_verify(prev, data, tag) {
                return true;
            }
        }

        false
    }
}

/// Server-side token state for a device.
///
/// This struct maintains the server's view of a device's token state,
/// including the device ID, current and previous tokens, sequence number,
/// and last rotation timestamp.
pub struct ServerTokenState {
    device_id: [u8; 16],
    current: [u8; 32],
    previous: Option<[u8; 32]>,
    sequence: u64,
    last_rotation: u64,
}

impl ServerTokenState {
    /// Creates a new server token state for a device.
    ///
    /// # Arguments
    ///
    /// * `device_id` - Unique identifier for the device
    /// * `initial_seed` - Initial token seed (must match client's seed)
    ///
    /// # Example
    ///
    /// ```
    /// use avon_crypto::token::ServerTokenState;
    ///
    /// let device_id = [0x01u8; 16];
    /// let seed = [0x42u8; 32];
    /// let state = ServerTokenState::new(device_id, seed);
    /// ```
    pub fn new(device_id: [u8; 16], initial_seed: [u8; 32]) -> Self {
        Self {
            device_id,
            current: initial_seed,
            previous: None,
            sequence: 0,
            last_rotation: 0,
        }
    }

    /// Returns the device ID.
    pub fn device_id(&self) -> &[u8; 16] {
        &self.device_id
    }

    /// Returns the current sequence number.
    pub fn sequence(&self) -> u64 {
        self.sequence
    }

    /// Returns the timestamp of the last rotation.
    pub fn last_rotation(&self) -> u64 {
        self.last_rotation
    }

    /// Returns a reference to the current token.
    pub fn current(&self) -> &[u8; 32] {
        &self.current
    }

    /// Generates rotation input for initiating a token rotation.
    ///
    /// The server generates a random nonce and creates a `TokenRotationInput`
    /// with a placeholder client nonce (all zeros). The client will fill in
    /// their own nonce.
    ///
    /// # Returns
    ///
    /// A tuple of (TokenRotationInput, server_nonce).
    ///
    /// # Example
    ///
    /// ```
    /// use avon_crypto::token::ServerTokenState;
    ///
    /// let mut state = ServerTokenState::new([0x01u8; 16], [0x42u8; 32]);
    /// let (input, server_nonce) = state.generate_rotation_input();
    ///
    /// assert_eq!(input.server_nonce, server_nonce);
    /// ```
    pub fn generate_rotation_input(&self) -> (TokenRotationInput, [u8; 32]) {
        let server_nonce = random_bytes_fixed::<32>().unwrap_or([0u8; 32]);
        let timestamp = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs())
            .unwrap_or(0);

        let input = TokenRotationInput {
            server_nonce,
            client_nonce: [0u8; 32], // Client will provide their nonce
            timestamp,
        };

        (input, server_nonce)
    }

    /// Completes a token rotation with the given input.
    ///
    /// This should be called after the client has provided their nonce
    /// and the full rotation input is available.
    ///
    /// # Returns
    ///
    /// The new current token.
    ///
    /// # Example
    ///
    /// ```
    /// use avon_crypto::token::{ServerTokenState, TokenRotationInput};
    ///
    /// let mut state = ServerTokenState::new([0x01u8; 16], [0x42u8; 32]);
    /// let input = TokenRotationInput::new([0u8; 32], [1u8; 32], 1000);
    ///
    /// let new_token = state.complete_rotation(&input);
    /// assert_eq!(state.sequence(), 1);
    /// ```
    pub fn complete_rotation(&mut self, input: &TokenRotationInput) -> [u8; 32] {
        let new_token = derive_next_token(
            &self.current,
            &input.server_nonce,
            &input.client_nonce,
            input.timestamp,
            self.sequence,
        );

        self.previous = Some(self.current);
        self.current = new_token;
        self.sequence += 1;
        self.last_rotation = input.timestamp;

        new_token
    }

    /// Verifies a token against the current state.
    ///
    /// Returns `Current` if the token matches the current token,
    /// `Previous` if it matches the previous token (grace period),
    /// or `Invalid` if it matches neither.
    pub fn verify(&self, token: &[u8; 32]) -> TokenVerifyResult {
        if constant_time_eq(&self.current, token) {
            return TokenVerifyResult::Current;
        }

        if let Some(ref prev) = self.previous {
            if constant_time_eq(prev, token) {
                return TokenVerifyResult::Previous;
            }
        }

        TokenVerifyResult::Invalid
    }

    /// Verifies an authentication tag over the given data.
    ///
    /// Tries the current token first, then the previous token if available.
    /// Uses constant-time comparison.
    pub fn verify_auth_tag(&self, data: &[u8], tag: &[u8; 32]) -> bool {
        // Try current token
        if hmac_sha256_verify(&self.current, data, tag) {
            return true;
        }

        // Try previous token if available
        if let Some(ref prev) = self.previous {
            if hmac_sha256_verify(prev, data, tag) {
                return true;
            }
        }

        false
    }
}

/// Derives the next token from the current state and rotation input.
fn derive_next_token(
    current: &[u8; 32],
    server_nonce: &[u8; 32],
    client_nonce: &[u8; 32],
    timestamp: u64,
    sequence: u64,
) -> [u8; 32] {
    // Build input key material: current || server_nonce || client_nonce || timestamp || sequence
    let mut ikm = Vec::with_capacity(32 + 32 + 32 + 8 + 8);
    ikm.extend_from_slice(current);
    ikm.extend_from_slice(server_nonce);
    ikm.extend_from_slice(client_nonce);
    ikm.extend_from_slice(&timestamp.to_le_bytes());
    ikm.extend_from_slice(&sequence.to_le_bytes());

    // Derive new token using HKDF-SHA256
    let derived = hkdf_sha256(&ikm, None, TOKEN_ROTATE_INFO, 32)
        .expect("HKDF should not fail with valid parameters");

    let mut result = [0u8; 32];
    result.copy_from_slice(&derived);
    result
}

/// Constant-time comparison of two byte arrays.
fn constant_time_eq(a: &[u8; 32], b: &[u8; 32]) -> bool {
    let mut diff = 0u8;
    for (x, y) in a.iter().zip(b.iter()) {
        diff |= x ^ y;
    }
    diff == 0
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_new_token() {
        let seed = [0x42u8; 32];
        let token = RotatingToken::new(seed);
        assert_eq!(token.current(), &seed);
        assert_eq!(token.sequence(), 0);
    }

    #[test]
    fn test_rotate_changes_token() {
        let mut token = RotatingToken::new([0x42u8; 32]);
        let input = TokenRotationInput::new([0u8; 32], [1u8; 32], 1000);

        let old_token = *token.current();
        let new_token = token.rotate(&input);

        assert_ne!(new_token, old_token);
        assert_eq!(token.current(), &new_token);
        assert_eq!(token.sequence(), 1);
    }

    #[test]
    fn test_verify_current() {
        let token = RotatingToken::new([0x42u8; 32]);
        let current = *token.current();

        assert!(matches!(token.verify(&current), TokenVerifyResult::Current));
    }

    #[test]
    fn test_verify_previous_after_rotation() {
        let mut token = RotatingToken::new([0x42u8; 32]);
        let old_token = *token.current();

        let input = TokenRotationInput::new([0u8; 32], [1u8; 32], 1000);
        token.rotate(&input);

        assert!(matches!(
            token.verify(&old_token),
            TokenVerifyResult::Previous
        ));
    }

    #[test]
    fn test_verify_invalid() {
        let token = RotatingToken::new([0x42u8; 32]);
        let invalid = [0xFFu8; 32];

        assert!(matches!(token.verify(&invalid), TokenVerifyResult::Invalid));
    }

    #[test]
    fn test_auth_tag_roundtrip() {
        let token = RotatingToken::new([0x42u8; 32]);
        let data = b"test data";
        let tag = token.compute_auth_tag(data);

        assert!(token.verify_auth_tag(data, &tag));
    }

    #[test]
    fn test_auth_tag_wrong_data() {
        let token = RotatingToken::new([0x42u8; 32]);
        let data = b"test data";
        let tag = token.compute_auth_tag(data);

        assert!(!token.verify_auth_tag(b"wrong data", &tag));
    }

    #[test]
    fn test_constant_time_eq() {
        let a = [0x42u8; 32];
        let b = [0x42u8; 32];
        let c = [0x43u8; 32];

        assert!(constant_time_eq(&a, &b));
        assert!(!constant_time_eq(&a, &c));
    }
}
