apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "avon.gateway.fullname" . }}-config
  labels:
    {{- include "avon.gateway.labels" . | nindent 4 }}
data:
  RUST_LOG: "info"
  GATEWAY_PORT: "{{ .Values.gateway.service.port }}"
  CONTROL_SERVICE_URL: "{{ include "avon.control.fullname" . }}:{{ .Values.control.service.port }}"
  CA_SERVICE_URL: "{{ include "avon.ca.fullname" . }}:{{ .Values.ca.service.port }}"
