[package]
name = "avon-agent"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
description = "AVON Endpoint Agent"

[[bin]]
name = "avon-agent"
path = "src/main.rs"

[dependencies]
tokio.workspace = true
serde.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true
anyhow.workspace = true
avon-crypto.workspace = true
avon-protocol.workspace = true
avon-common.workspace = true
