apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "avon.auth.fullname" . }}-config
  labels:
    {{- include "avon.auth.labels" . | nindent 4 }}
data:
  RUST_LOG: "info"
  AUTH_PORT: "{{ .Values.auth.service.port }}"
  CA_SERVICE_URL: "{{ include "avon.ca.fullname" . }}:{{ .Values.ca.service.port }}"
  POSTGRESQL_HOST: {{ include "avon.postgresql.host" . | quote }}
  REDIS_HOST: {{ include "avon.redis.host" . | quote }}
