[package]
name = "avon-protocol"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
description = "Wire protocol definitions for AVON"

[dependencies]
prost.workspace = true
prost-types.workspace = true
tonic.workspace = true
uuid.workspace = true
thiserror.workspace = true

[build-dependencies]
tonic-build = "0.13"

[lints]
workspace = true
