apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "avon.policyEngine.fullname" . }}-config
  labels:
    {{- include "avon.policyEngine.labels" . | nindent 4 }}
data:
  LOG_LEVEL: "info"
  POLICY_ENGINE_PORT: "{{ .Values.policyEngine.service.port }}"
  AUTH_SERVICE_URL: "{{ include "avon.auth.fullname" . }}:{{ .Values.auth.service.port }}"
  POSTGRESQL_HOST: {{ include "avon.postgresql.host" . | quote }}
  REDIS_HOST: {{ include "avon.redis.host" . | quote }}
