"""Generated gRPC service stubs for policy service.

This is a stub file that would normally be generated by protoc.
For production use, run: python -m grpc_tools.protoc -I../../proto --python_out=. --grpc_python_out=. policy_service.proto
"""

import grpc

from policy_engine.api import policy_pb2


class PolicyServiceStub:
    """Client stub for PolicyService."""

    def __init__(self, channel: grpc.Channel):
        self.EvaluatePolicy = channel.unary_unary(
            "/avon.v1.PolicyService/EvaluatePolicy",
            request_serializer=lambda x: x,
            response_deserializer=lambda x: x,
        )
        self.GetDevicePods = channel.unary_unary(
            "/avon.v1.PolicyService/GetDevicePods",
            request_serializer=lambda x: x,
            response_deserializer=lambda x: x,
        )
        self.InvalidateCache = channel.unary_unary(
            "/avon.v1.PolicyService/InvalidateCache",
            request_serializer=lambda x: x,
            response_deserializer=lambda x: x,
        )


class PolicyServiceServicer:
    """Server interface for PolicyService."""

    async def EvaluatePolicy(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    async def GetDevicePods(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    async def InvalidateCache(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_PolicyServiceServicer_to_server(servicer, server):
    """Add PolicyServiceServicer to a gRPC server."""
    rpc_method_handlers = {
        "EvaluatePolicy": grpc.unary_unary_rpc_method_handler(
            servicer.EvaluatePolicy,
            request_deserializer=lambda x: x,
            response_serializer=lambda x: x,
        ),
        "GetDevicePods": grpc.unary_unary_rpc_method_handler(
            servicer.GetDevicePods,
            request_deserializer=lambda x: x,
            response_serializer=lambda x: x,
        ),
        "InvalidateCache": grpc.unary_unary_rpc_method_handler(
            servicer.InvalidateCache,
            request_deserializer=lambda x: x,
            response_serializer=lambda x: x,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "avon.v1.PolicyService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
