"""Generated protocol buffer code for policy service.

This is a stub file that would normally be generated by protoc.
For production use, run: python -m grpc_tools.protoc -I../../proto --python_out=. --grpc_python_out=. policy_service.proto
"""

from enum import IntEnum
from typing import Optional


POLICY_ACTION_UNSPECIFIED = 0
POLICY_ACTION_ALLOW = 1
POLICY_ACTION_DENY = 2


class EvaluatePolicyRequest:
    """Request message for EvaluatePolicy RPC."""

    def __init__(
        self,
        source_device_id: bytes = b"",
        destination_device_id: bytes = b"",
        source_posture=None,
        destination_posture=None,
        context: Optional[dict] = None,
    ):
        self.source_device_id = source_device_id
        self.destination_device_id = destination_device_id
        self.source_posture = source_posture
        self.destination_posture = destination_posture
        self.context = context or {}

    def HasField(self, field_name: str) -> bool:
        if field_name == "source_posture":
            return self.source_posture is not None
        if field_name == "destination_posture":
            return self.destination_posture is not None
        return False


class EvaluatePolicyResponse:
    """Response message for EvaluatePolicy RPC."""

    def __init__(
        self,
        action: int = POLICY_ACTION_UNSPECIFIED,
        policy_id: str = "",
        reason: str = "",
        evaluation_time_ms: float = 0.0,
        matched_policies_count: int = 0,
        source_pods: Optional[list] = None,
        destination_pods: Optional[list] = None,
    ):
        self.action = action
        self.policy_id = policy_id
        self.reason = reason
        self.evaluation_time_ms = evaluation_time_ms
        self.matched_policies_count = matched_policies_count
        self.source_pods = source_pods or []
        self.destination_pods = destination_pods or []


class GetDevicePodsRequest:
    """Request message for GetDevicePods RPC."""

    def __init__(
        self,
        device_id: bytes = b"",
        expand_hierarchy: bool = False,
    ):
        self.device_id = device_id
        self.expand_hierarchy = expand_hierarchy


class GetDevicePodsResponse:
    """Response message for GetDevicePods RPC."""

    def __init__(self, pod_ids: Optional[list] = None):
        self.pod_ids = pod_ids or []


class InvalidateCacheRequest:
    """Request message for InvalidateCache RPC."""

    def __init__(
        self,
        device_id: str = "",
        pod_id: str = "",
        all: bool = False,
    ):
        self.device_id = device_id
        self.pod_id = pod_id
        self.all = all

    def WhichOneof(self, oneof_name: str) -> Optional[str]:
        if oneof_name == "target":
            if self.device_id:
                return "device_id"
            if self.pod_id:
                return "pod_id"
            if self.all:
                return "all"
        return None


class InvalidateCacheResponse:
    """Response message for InvalidateCache RPC."""

    def __init__(self, success: bool = False, message: str = ""):
        self.success = success
        self.message = message


class DevicePosture:
    """Device posture message."""

    def __init__(
        self,
        os_version: str = "",
        agent_version: str = "",
        firewall_enabled: bool = False,
        disk_encrypted: bool = False,
    ):
        self.os_version = os_version
        self.agent_version = agent_version
        self.firewall_enabled = firewall_enabled
        self.disk_encrypted = disk_encrypted
