{{- if .Values.control.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "avon.control.fullname" . }}
  labels:
    {{- include "avon.control.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
